name: Deploy from main branch

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.husky/**'
      - '.vscode/**'
      - 'docs/**'
      - 'jest/**'
      - 'mocks/**'
      - 'playwright/**'
      - 'stubs/**'
      - 'tools/**'
  workflow_dispatch:


jobs:
  publish_image:
    name: Publish Docker image
    uses: './.github/workflows/publish-image.yml'
